# Generated by Django 3.1.7 on 2021-03-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(max_length=255, verbose_name='Nombre de la categoria'),
        ),
        migrations.AlterField(
            model_name='color',
            name='nombre_color',
            field=models.CharField(max_length=255, verbose_name='Nombre del color'),
        ),
    ]
