# Generated by Django 3.1.7 on 2021-03-29 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='preferencia',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer'), ('T', 'Todo')], max_length=1, verbose_name='Qué te interesa más'),
        ),
        migrations.CreateModel(
            name='Caro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_total', models.FloatField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='tienda.producto')),
            ],
        ),
    ]
