# Generated by Django 3.1.7 on 2021-03-29 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0006_auto_20210329_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_desquento', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_produc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='tienda.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Caro',
        ),
    ]
